### ISSUE TITLE
Completion instead of menu

### ISSUE THREAD

**Issue by phdru** [mug896/virtualbox-bash-completion#2]
`VBoxManage startvm`<kbd>Tab</kbd><kbd>Tab</kbd> shows a menu like this:

    00) "CentOS_5" {823e448d-3df8-482d-bfd5-f3bb192fb2f3}
    01) "Debian_9" {bdd82dd8-7381-4b33-b3ce-99ad44fb714c}
    02) "OpenSUSE" {a2844c97-0810-45fa-ba9c-8fa92602464e}

I prefer to type `VBoxManage startvm D`<kbd>Tab</kbd> and have completion to complete it to `Debian` instead of the menu.

**Comment by mug896** [comment]
`vmname` completion needs `"` character in front of `D` like this

> vboxmanage startvm "D<kbd>tab</kbd>

**Comment by phdru** [comment]
> `vmname` completion needs `"` character in front of `D` like this
> 
> > vboxmanage startvm "Dtab</kbd>Tab</kbd>

Works for me, thanks! Should I remove the pull request?

**Comment by mug896** [comment]
yes. i think so

**Comment by phdru** [comment]
Thank you very much for the code and the help!
